# Generated by Django 4.2.7 on 2023-11-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do sonho', max_length=50, verbose_name='dream_title')),
                ('time', models.CharField(choices=[('DIA', 'Diurno'), ('NOITE', 'Noturno'), ('INDEFINIDO', 'Não presenciado')], default='INDEFINIDO', help_text='dia / noite no sonho', max_length=50, verbose_name='Estado do dia no sonho')),
            ],
        ),
    ]
