# Generated by Django 4.2.7 on 2023-12-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_remove_dream_time_dream_author_dream_dream_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='dream_date'),
        ),
    ]
