# Generated by Django 4.2.7 on 2023-12-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_dream_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='feeling',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Feliz', 'Feliz'), ('Triste', 'Triste'), ('Raivoso', 'Raivoso'), ('Asssustado', 'Asssustado'), ('Indefinido', 'Indefinido'), ('Múltiplos', 'Múltiplos')], default='Indefinido', help_text='Sentimento', max_length=20, verbose_name='feeling'),
        ),
        migrations.AddField(
            model_name='dream',
            name='lucid',
            field=models.CharField(choices=[('Não Lúcido', 'Não Lúcido'), ('Parcialmente Lúcido', 'Parcialmente Lúcido'), ('Lúcido', 'Lúcido')], default='Não Lúcido', help_text='Lucidez', max_length=20, verbose_name='lucid'),
        ),
        migrations.AddField(
            model_name='dream',
            name='period',
            field=models.CharField(choices=[('Dia', 'Dia'), ('Noite', 'Noite'), ('Indefinido', 'Indefinido'), ('Múltiplos', 'Múltiplos')], default='Indefinido', help_text='Sonho / Pesadelo help text', max_length=20, verbose_name='period'),
        ),
        migrations.AddField(
            model_name='dream',
            name='public',
            field=models.BooleanField(default=False, help_text='Sonho Público', verbose_name='public'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='date',
            field=models.DateField(verbose_name='dream_date'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dream_type',
            field=models.CharField(choices=[('SONHO', 'Sonho'), ('PESADELO', 'Pesadelo')], default='SONHO', help_text='Tipo de Sonho', max_length=10, verbose_name='dream_type'),
        ),
    ]
